name: Build and Deploy with BuildKit

on:
  push:
    branches:
      - devops

env:
  DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  REGISTRY_GHCR: ghcr.io
  REGISTRY_GITLAB: registry.gitlab.com
  IMAGE_NAME_DOCKER: ${{ secrets.DOCKER_USERNAME }}/demo-app
  IMAGE_NAME_GHCR: ghcr.io/${{ github.repository }}/demo-app
  IMAGE_NAME_GITLAB: registry.gitlab.com/${{ github.repository }}/demo-app

jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run BuildKit container to build images
        uses: addnab/docker-run-action@v3
        with:
          image: moby/buildkit:rootless
          options: >
            --rm
            --security-opt seccomp=unconfined
            --security-opt apparmor=unconfined
            -v ${{ github.workspace }}:/repo
          run: |
            export BUILDKITD_FLAGS="--allow-insecure-entitlement security.insecure"
            
            # Start rootless buildkitd
            buildkitd-rootless.sh &
            sleep 5  # give it a few seconds to start

            cd /repo

            # Optional: write Dockerfile from secret
            echo "${{ secrets.DOCKERFILE_DEMO_APP }}" > Dockerfile

            # Login to Docker registries
            buildctl login docker.io --username $DOCKER_HUB_USERNAME --password $DOCKER_HUB_PASSWORD
            # buildctl login ghcr.io --username $GITHUB_ACTOR --password ${{ secrets.GITHUB_TOKEN }}
            # buildctl login registry.gitlab.com --username ${{ secrets.GITLAB_USER }} --password ${{ secrets.GITLAB_TOKEN }}

            # Build and push Docker images
            buildctl build \
              --frontend dockerfile.v0 \
              --local context=. \
              --local dockerfile=. \
              --output type=image,name=$IMAGE_NAME_DOCKER:latest,push=true 
              # --output type=image,name=$IMAGE_NAME_GHCR:latest,push=true \
              # --output type=image,name=$IMAGE_NAME_GITLAB:latest,push=true
