name: Build and Deploy with BuildKit

on:
  push:
    branches:
      - main

env:
  DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  REGISTRY_GHCR: ghcr.io
  REGISTRY_GITLAB: registry.gitlab.com
  IMAGE_NAME_DOCKER: ${{ secrets.DOCKER_USERNAME }}/demo-app
  IMAGE_NAME_GHCR: ghcr.io/${{ github.repository }}/demo-app
  IMAGE_NAME_GITLAB: registry.gitlab.com/${{ github.repository }}/demo-app
  DOCKERFILE: ${{ secrets.DOCKERFILE }}