name: Build and Deploy with BuildKit Rootless

on:
  push:
    branches:
      - devops

jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up BuildKit rootless container
        uses: addnab/docker-run-action@v3
        with:
          image: moby/buildkit:rootless
          options: --rm --privileged --security-opt seccomp=unconfined --security-opt apparmor=unconfined
          run: |
            mkdir -p /tmp/repo
            cp -r . /tmp/repo
            cd /tmp/repo

            # Write Dockerfile if needed from secret
            echo "${{ secrets.DOCKERFILE_CONTENT }}" > Dockerfile

            # Log in to registries
            buildctl login docker.io --username "${{ secrets.DOCKER_USERNAME }}" --password "${{ secrets.DOCKER_PASSWORD }}"
            buildctl login ghcr.io --username "${{ github.actor }}" --password "${{ secrets.GHCR_TOKEN }}"
            buildctl login registry.gitlab.com --username "${{ secrets.GITLAB_USER }}" --password "${{ secrets.GITLAB_TOKEN }}"

            # Build and push images to multiple registries
            buildctl build \
              --frontend dockerfile.v0 \
              --local context=. \
              --local dockerfile=. \
              --output type=image,name=docker.io/${{ secrets.DOCKER_USERNAME }}/demo-app:latest,push=true \
              --output type=image,name=ghcr.io/${{ github.repository_owner }}/demo-app:latest,push=true \
              --output type=image,name=registry.gitlab.com/${{ github.repository_owner }}/demo-app:latest,push=true
