name: Build and Deploy with BuildKit Rootless

on:
  push:
    branches:
      - devops

env:
  IMAGE_NAME_DOCKER: ${{ secrets.DOCKER_USERNAME }}/demo-app
  IMAGE_NAME_GHCR: ghcr.io/${{ github.repository }}/demo-app
  IMAGE_NAME_GITLAB: registry.gitlab.com/${{ github.repository }}/demo-app

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Upload repo as artifact for next job
      - name: Upload repository as artifact
        uses: actions/upload-artifact@v4
        with:
          name: repo
          path: .

  build-push:
    runs-on: ubuntu-latest
    needs: checkout
    steps:
      # 1️⃣ Download repo artifact
      - name: Download repository artifact
        uses: actions/download-artifact@v4
        with:
          name: repo
          path: ./repo

      # 0️⃣ Write Dockerfile before BuildKit
      - name: Write Dockerfile from Secret
        run: echo "${{ secrets.DOCKERFILE_DEMO_APP }}" > ./repo/Dockerfile

      # 2️⃣ Login to Docker Hub
      - name: Docker Hub Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # # 3️⃣ Login to GitHub Container Registry
      # - name: GHCR Login
      #   uses: docker/login-action@v3
      #   with:
      #     registry: ghcr.io
      #     username: ${{ github.actor }}
      #     password: ${{ secrets.GITHUB_TOKEN }}

      # # 4️⃣ Login to GitLab Registry
      # - name: GitLab Login
      #   uses: docker/login-action@v3
      #   with:
      #     registry: registry.gitlab.com
      #     username: ${{ secrets.GITLAB_USER }}
      #     password: ${{ secrets.GITLAB_TOKEN }}

      # 5️⃣ Build and Push Images in rootless BuildKit container
      - name: Build and Push Images
        uses: addnab/docker-run-action@v4
        with:
          image: moby/buildkit:rootless
          options: --rm \
                   --security-opt seccomp=unconfined \
                   --security-opt apparmor=unconfined \
                   -v $HOME/.docker:/root/.docker \# mount Docker credentials
                   -v ${{ github.workspace }}/repo:/repo --rm
          run: |
            cd ./repo

            # Build and push images to all registries
            buildctl build \
              --frontend dockerfile.v0 \
              --local context=. \
              --local dockerfile=. \
              --output type=image,name=${IMAGE_NAME_DOCKER}:latest,push=true
              # --output type=image,name=${IMAGE_NAME_GHCR}:latest,push=true \
              # --output type=image,name=${IMAGE_NAME_GITLAB}:latest,push=true